### ISSUE TITLE
compile to javascript

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#22]
We need to ensure that the project and it's examples can compile to javascript.

**Comment by zoechi** [comment]
I have tried a bunch of things but none of them worked sufficiently.
- pub build currently works only with web directory but not with web directory
  - After creating a symbolic link from web to example pub build worked but the output is useless
    - Chrome and Firefox try to execute dart files instead of js files
    - Several different JS error messages when executing the genereated sites
- dart build.dart --deploy led to similar results
  - build.dart with build() 
  - build.dart with lint()
- build from Editor context menu (doesn't work either)
  - and run as Javascript

Another problem is caused by elements which import elements from another package (polymer_elements <==> polymer_ui_elements).
This is not yet supported by Dart (I had to use an import path that results in errors in Editor and dart2js but works in Dartium)

**Comment by ErikGrimes** [comment]
Yes.  I've had similar luck trying to get compilation into javascript
working.  I recall seeing messages around on the board. I'll reach out to
the group to see assess the current state of compiling polymer libraries
and applications.

**Comment by ErikGrimes** [comment]
I'm moving this to later.  Compiling to javascript right now is it too much of a headache. We can wait for this area to get better.
- [web ui discussion](https://groups.google.com/a/dartlang.org/forum/#!topic/web-ui/jdoLc_roMLI)
- [14730](https://code.google.com/p/dart/issues/detail?id=14730)
- [14763](https://code.google.com/p/dart/issues/detail?id=14673)

**Comment by zoechi** [comment]
this works for most elements
the pubspec.yaml needs a transformers configuration without entrypoints like

```
 transformers:
 - polymer:
     entry_points:
```

I also built a temporary package (polymer_elements_examples, for polymer_ui_elements_examples) to work around current pub build limitations. I'll check the repositories are available.
