### ISSUE TITLE
example files

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#3]
The files in your example directory have _demo and _example suffixes.
I moved the index.html files from the elements I ported to the example directory and just named them according to the element name.
I am in favor of a suffix because in the editor tabs the files are difficult to distinguish without. 
Has your demo and example suffix a different meaning?

**Comment by ErikGrimes** [comment]
The 'element-demo' is the polymer app, 'element-example' is that apps main element.  I didn't put much thought into them, I just needed to differentiate them.  I had everything in the same directory due to issues with the editor not being able to find source while debugging.  It's also not possible to implement some of the polymer examples within a single index.html file, so I've taken to haven an app entry point file and a main app element for all examples for consistency.  I think this is also the recommended way to structure apps for polymer.dart now.  Any thoughts on better names?

**Comment by zoechi** [comment]
I went for a html/dart file combination for each element.
AFAIK editor support (intellisense, ...) is now supported in script tags
but I won't do this because debugging is not supported for inline scripts.
Keeping the element's html in index.html and creating dart files for the
element's dart code seems weird to me.

I generally name the main element app-element.
When we have a distinct src/xxx directory for each entry page the xxx
tells what it's about and app-element tells this is the "main" element -
short and simple.

Günter
