### ISSUE TITLE
polymer_selector has some warnings

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#37]
Do you see these warings too?
return this.$['selection'].selection;
(There is no such getter 'selection' in 'Element' 
and 4 more)

**Comment by ErikGrimes** [comment]
This is because there is no import for polymer_selection.  Dartium and imports in custom element files don't always play well together.  See this discussion thread [here](https://groups.google.com/a/dartlang.org/forum/#!searchin/web-ui/canonicalization/web-ui/8eavxm41Vtw/sjbcQaJ_6lAJ).  I'm not sure if they've fixed it yet, but dart is optionally typed and I know it works right now, so I'm inclined to leave it and revisit at a later date.

**Comment by zoechi** [comment]
blocked on #42
