### ISSUE TITLE
How to use polymer flex-layout non-ui element.

### ISSUE THREAD

**Issue by st-clair-clarke** [bwu-dart-graveyard/polymer_elements#75]
Hello Erik,
As suggested by you I am posting a request here. Your flex-layout port example is shown below:

```
<!DOCTYPE html>
<html>
<head>
  <title>polymer-flex-layout</title>
  <link rel="import" href="packages/polymer_elements/polymer_flex_layout/polymer_flex_layout.html">
  <link rel="import" href="packages/polymer_elements/polymer_flex_layout/polymer_flex_panel.html">
  <link rel="import" href="src/polymer_flex_layout/flex_css.html">
  <link rel="import" href="src/polymer_flex_layout/flex_container.html">
  <link rel="import" href="src/polymer_flex_layout/flex_nonvisual.html">

  <script type="application/dart">
    export 'package:polymer/init.dart';</script>
  <script src="packages/browser/dart.js"></script>

  <style>

    body {
      font-size: 20px;
    }

    flex-css, flex-container, flex-nonvisual {
      height: 500px;
    }
  </style>
</head>
<body>
  <h3>polymer-flex-layout.css</h3>
  <flex-css></flex-css>
  <br>
  <h3>polymer-flex-panel element</h3>
  <flex-container>
    <input id='zoo', name='zoo' type='text'>

  </flex-container>
  <br>
  <h3>polymer-flex-layout element</h3>
  <flex-nonvisual></flex-nonvisual>
</body>
</html>
```

I added the input, but I don't know what to do next. How do I use the port. Could you please added some widgets in the example with layout placement so we could get a better understanding of how the port works?. I look at the example at polymer.org, but that did not help me either.

Thanks

**Comment by zoechi** [comment]
Hi,
thank you very much for your interest in polymer_elements.
It is a great motivation for us :)

As you can see when you run the polymer_flex_layout example that polymer-flex-layout is not yet fully working.
There are some issues with CSS not being applied fully, due to some limitation in recent Dart/Dartium releases. 
We check regularly with each Dart update and update the status in the README.md file.

The example/polymer_flex_layout.html imports the three custom elements from example/src/polymer_flex_layout folder (flex_container, flex_css, flex_nonvisual) where the flex-layout is actually applied. Maybe this is what you are looking for.

The flex_css example seems to work all right already [flex_css.html](https://github.com/ErikGrimes/polymer_elements/blob/master/example/src/polymer_flex_layout/flex_css.html)

I hope this helps a bit.
If you have further questions please don't hesitate to ask.

Günter
